root = "."
tmp_dir = "tmp"

[build]
# 修改构建命令，确保先执行 swag init
cmd = "swag init && go build -o ./tmp/main.exe ."
# 删除 pre_cmd，直接将 swag init 集成到 cmd 中
bin = "tmp\\main.exe"
full_bin = "tmp\\main.exe"
# 只需要监听 .go 文件的更改
include_ext = ["go"]
# 忽略这些文件夹
exclude_dir = ["assets", "tmp", "vendor", "docs"]
# 忽略这些文件
exclude_file = []
# 主程序入口
main = "main.go"
# 延迟时间
delay = 1000
# 发生错误时停止运行
stop_on_error = true
# 发送中断信号后清理
send_interrupt = false
# 退出时发送终止信号
kill_delay = "0s"

[log]
# 显示日志时间
time = true

[color]
# 自定义每个部分的颜色
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# 退出时清理临时目录
clean_on_exit = true 